name: MQL4 Compile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Build 509 Compiler
      run: |
        Invoke-WebRequest https://download.mql5.com/cdn/web/mt4/mt4build509.exe -OutFile mt4build509.exe
        .\mt4build509.exe /S /D="C:\MT4 Build 509"

    - name: Compile MQL4 code
      shell: cmd
      run: |
        "C:\MT4 Build 509\metaeditor.exe" /compile:"${{ github.workspace }}/ema-cross-ea.mq4"
